# Welcome to Jekyll!
# This config file contains settings for the site.

# Basic Site Settings
locale: "en-US"
title: "My Education Platform"
title_separator: "-"
description: "Personal description"
url: "https://Sharma-eng-cli.github.io"
baseurl: ""
repository: "academicpages/academicpages.github.io"

# Author Information
author:
  name: "Dr. Jagpreet Singh"
  bio: "Assistant Professor in Computer Science & Engineering at IIT Ropar."
  location: "Rupnagar, Punjab, India"
  employer: "Indian Institute of Technology Ropar"
  uri: "https://www.iitrpr.ac.in/jagpreet-singh"
  email: "jagpreets@iitrpr.ac.in"
  github: "academicpages"
  googlescholar: "https://scholar.google.com/citations?user=8qUKIE4AAAAJ"

# Publications Category Titles
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# Site Settings
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

# Comments Settings
comments:
  provider: false

# SEO and Analytics
analytics:
  provider: "false"

google_site_verification: ""
bing_site_verification: ""

# Pagination Settings (Ensuring it Works)
paginate: 10
paginate_path: "/publications/page:num/"

# Collections
collections:
  publications:
    output: true
    permalink: "/publications/:path/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Permalinks
permalink: "/:categories/:title/"

# Markdown Processing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6

# Output Settings
encoding: "utf-8"
timezone: Etc/UTC
